services:
  # MongoDB Container
  mongodb:
    image: mongo:latest
    container_name: project_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - project_network

  # Redis Container
  redis:
    image: redis:alpine
    container_name: project_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      - project_network

  # PostgreSQL with PostGIS Container
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: project_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pickmypit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local

